apiVersion: apps.my.domain/v1alpha1
kind: MyApp
metadata:
  labels:
    app.kubernetes.io/name: kube-operator-test
    app.kubernetes.io/managed-by: kustomize
  name: myapp-sample
spec:
  # TODO(user): Add fields here
